[methods]

    [methods.fetch_marks_for_period]
    education = 427304
    date_from = "04.11.2021"
    date_to = "27.12.2021"
    limit = 200

[subjects]
113703 = "Английский язык"
113704 = "Немецкий язык"
11249 = "ОБЖ"
